data:
  content_folder: C:\Users\Gianluca\Desktop\style_transfer\content
  style_folder: C:\Users\Gianluca\Desktop\style_transfer\style
  output_folder: C:\Users\Gianluca\Desktop\style_transfer\output
  img_size: [3, 1080, 1080]

weights:
  alpha: 1
  beta: 1e6

train:
  lr: 1e-3
  steps: 300
  print_every: 20

model: vgg19
device: cuda

layers:
  content:
    '21': conv4_2
  style:
    '0': conv1_1
    '5': conv2_1
    '10': conv3_1
    '19': conv4_1
    '28': conv5_1